### ISSUE TITLE
Tree-Sitter ist Teil des PUBLIC Interfaces

### ISSUE THREAD

**Issue by ThomasWitte** [sp-uulm/MiniLua#13]
Ein abhängiges Projekt versucht immer gegen Tree-Sitter zu linken, weil das als PUBLIC library exportiert wird (src/CMakeLists.txt:21), aber nie irgendwo installiert wird (und auch nicht installiert werden sollte).

Das Interface sollte stattdessen PRIVATE sein und die Tests entsprechend gefixt werden.

**Comment by Lythenas** [comment]
Related to #11
