### ISSUE TITLE
Move Tree-Sitter Wrapper to its own repository

### ISSUE THREAD

**Issue by ThomasWitte** [sp-uulm/MiniLua#19]
This is just an idea. The tree sitter wrapper looks really promising and might be of great interest for other projects using tree-sitter. As far as I understand tree-sitter's architecture, the language bindings are kept in repositories named <language>-tree-sitter. I propose creating a seperate repository cpp-tree-sitter and moving the wrapper there.

**Comment by Lythenas** [comment]
I'm generally in favor of this. But we should talk about where to move it.

**Comment by ahlinc** [comment]
I've asked to specify a license for this repo here https://github.com/sp-uulm/MiniLua/issues/111 and actually interesting is the mentioned tree-sitter wrapper. @Lythenas could you move ahead this suggestion about separate repo with the clearly specified license for the code?

**Comment by Lythenas** [comment]
@ahlinc We are going to license the project under MIT (#112). And I will move the Tree-Sitter wrapper to it's own Repo. But I have some changes in another PR I want to merge first.

**Comment by ahlinc** [comment]
@Lythenas thank you!
