### ISSUE TITLE
Design the "public API"

### ISSUE THREAD

**Issue by Lythenas** [sp-uulm/MiniLua#20]
Create a design for the public API.

The public API should not expose any implementation details (like Tree-Sitter types). It should provide a good and easy to use abstraction (e.g. no `std::shared_ptr` or `std::variant` those are all implementation details). But the API should still be customizable enough for most use cases (e.g. adding custom lua functions to the interpreter).

**Comment by ThomasWitte** [comment]
I think a shared_ptr<SourceChange> or sth similar is ok for the public API. For variant and other more complex types I agree that at least a type alias should be used.

**Comment by ThomasWitte** [comment]
Value probably needs a hasOrigin method
