### ISSUE TITLE
Improvement of Block comments

### ISSUE THREAD

**Issue by tn4799** [sp-uulm/MiniLua#38]
Block comments are --[ then n times = and then [. To close there are ] n = and ]. 
This expression isn't catchable with a regular expression. At the moment only --[[ ]] is working for block comments. To improve this there should be an additional parser for block comments which should be triggered if --[ is found and then find the end of the block comment.

**Comment by Lythenas** [comment]
This should be fixed when we switch to Tree-Sitter.
